"""Convert HL7 QRY_A19 message to FHIR Bundle.

Autogenerated scaffold. Replace the logic inside `hl7_to_fhir`
with a real field‑level mapping.

Dependencies:
    pip install hl7apy fhir.resources
"""  # noqa: E501

from hl7apy import parser
from fhir.resources.bundle import Bundle

STUB_HL7_MESSAGE = """MSH|^~\\&|SendingApp|SendingFac|ReceivingApp|ReceivingFac|20250420130120||QRY|123456|P|2.5
PID|1||12345^^^MR||Doe^John||19800101|M
"""  # noqa: E501


def hl7_to_fhir(hl7_str: str) -> Bundle:
    """Stub converter. Extend this for full mapping."""
    bundle = Bundle.construct()
    bundle.type = "message"
    bundle.meta = {"tag": [{"code": "QRY_A19"}]}
    return bundle


if __name__ == "__main__":
    bundle = hl7_to_fhir(
        STUB_HL7_MESSAGE
    )
    print(bundle.json(indent=2))
